services:
  munin:
    image: egor045/munin
    container_name: munin
    environment:
      TZ: "Europe/Berlin"
      NODES: "node1:10.0.0.101 node2:10.0.0.102"
      SNMP_NODES: "10.0.0.11 10.0.0.12"
      SNMP_PLUGINS_EXCLUDED: "10.0.0.11:df,swap"
    ports:
      - 80:80
    volumes:
      - ./lib:/var/lib/munin
      - ./log:/var/log/munin
      - ./conf:/etc/munin/munin-conf.d
      - ./plugin:/etc/munin/plugin-conf.d
    restart: always
    stop_grace_period: 1m
